In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv(r"C:\Users\hp\Desktop\jupyter notebook\KNN Classifier\Zoo.csv")

In [3]:
df.shape


(101, 18)

In [4]:
df.head()


animal name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   

   type  
0     1  
1     1  
2     4  
3     1  
4     1

In [5]:
list(df)


['animal name',
 'hair',
 'feathers',
 'eggs',
 'milk',
 'airborne',
 'aquatic',
 'predator',
 'toothed',
 'backbone',
 'breathes',
 'venomous',
 'fins',
 'legs',
 'tail',
 'domestic',
 'catsize',
 'type']

In [5]:
Y = df["type"]
X= df.iloc[:,1:18]


In [6]:
df.dtypes
df_cat = df[['type']]
df_cat.head()


type
0     1
1     1
2     4
3     1
4     1

In [7]:
from sklearn.preprocessing import LabelEncoder
LE =LabelEncoder()
Y = LE.fit_transform(Y)
Y


array([0, 0, 3, 0, 0, 0, 0, 3, 3, 0, 0, 1, 3, 6, 6, 6, 1, 0, 3, 0, 1, 1,
       0, 1, 5, 4, 4, 0, 0, 0, 5, 0, 0, 1, 3, 0, 0, 1, 3, 5, 5, 1, 5, 1,
       0, 0, 6, 0, 0, 0, 0, 5, 4, 6, 0, 0, 1, 1, 1, 1, 3, 3, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 6, 3, 0, 0, 2, 6, 1, 1, 2, 6, 3, 1, 0, 6, 3, 1,
       5, 4, 2, 2, 3, 0, 0, 1, 0, 5, 0, 6, 1], dtype=int64)

In [9]:
from sklearn.preprocessing import StandardScaler 
SS = StandardScaler()
SS_X = SS.fit_transform(X)
SS_X
SS_X = pd.DataFrame(SS_X)


In [10]:
#Data partition
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(SS_X,Y,test_size=0.30,
                                                 random_state=11)

X_train.shape
X_test.shape

(31, 17)

In [11]:
#step5: Logistic regrssion

from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

logreg.fit(X_train,Y_train)

Y_pred_train = logreg.predict(X_train)
Y_pred_test = logreg.predict(X_test)


In [12]:
#step:6 metrics

from sklearn.metrics import accuracy_score
ac_train = accuracy_score(Y_train,Y_pred_train)
ac_test = accuracy_score(Y_test,Y_pred_test)

print("Training Accuracy:",ac_train.round(2))
print("Test Accuracy:",ac_test.round(2))


Training Accuracy: 1.0
Test Accuracy: 0.97


In [13]:
#cross validation

training_accuracy =[]
test_accuracy = []

for i in range (1,100):
    X_train,X_test,Y_train,Y_test = train_test_split(SS_X,Y,test_size=0.30,
                                                    random_state=i)
    logreg.fit(X_train,Y_train)
    Y_pred_train = logreg.predict(X_train)
    Y_pred_test = logreg.predict(X_test)
    training_accuracy.append(accuracy_score(Y_train,Y_pred_train))
    test_accuracy.append(accuracy_score(Y_test,Y_pred_test))
#pd.DataFrame(training_accuracy).hist()   
k1 = pd.DataFrame(training_accuracy)
k1.skew()
k1.mean()
print("Cross validation training results:",k1.mean().round(2))
#pd.DataFrame(test_accuracy).hist()   
k1 = pd.DataFrame(test_accuracy)
k1.skew()
k1.mean()
print("Cross validation test results:",k1.mean().round(2))


Cross validation training results: 0    1.0
dtype: float64
Cross validation test results: 0    0.94
dtype: float64


In [14]:
#k-fold cross validation


from sklearn.model_selection import KFold
KFold(n_splits=5)
KFold = KFold(n_splits=5)

for i in range(0,30):
    print(i)
for train_index,test_index in KFold.split(range(0,30)):
    print(test_index)
    print(train_index)
    
training_accuracy =[]
test_accuracy = []
for train_index,test_index in KFold.split(SS_X):
    X_train,X_test = SS_X.iloc[train_index],SS_X.iloc[test_index]
    Y_train,Y_test = Y[train_index],Y[test_index]
    logreg.fit(X_train,Y_train)
    Y_pred_train = logreg.predict(X_train)
    Y_pred_test = logreg.predict(X_test)
    training_accuracy.append(accuracy_score(Y_train,Y_pred_train))
    test_accuracy.append(accuracy_score(Y_test,Y_pred_test))

print("K-Fold Cross validation training results:",np.mean(training_accuracy).round(2))
print("K-Fold Cross validation test results:",np.mean(test_accuracy).round(2))


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
[0 1 2 3 4 5]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[ 6  7  8  9 10 11]
[ 0  1  2  3  4  5 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[12 13 14 15 16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 18 19 20 21 22 23 24 25 26 27 28 29]
[18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 24 25 26 27 28 29]
[24 25 26 27 28 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
K-Fold Cross validation training results: 1.0
K-Fold Cross validation test results: 0.93


In [15]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [17]:
import numpy as np

X_train = np.array(X_train)
X_test = np.array(X_test)

print(X_train.flags.c_contiguous)
print(X_test.flags.c_contiguous)
X_train = np.ascontiguousarray(X_train)
X_test = np.ascontiguousarray(X_test)
pip install --upgrade scikit-learn

# knn classifier with its accuracy
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=9)

   KNN.fit(X_train,Y_train)
   Y_pred_train = KNN.predict(X_train)
   Y_pred_test = KNN.predict(X_test)

SyntaxError: invalid syntax (2327066603.py, line 10)

In [15]:
#metrics
from sklearn.metrics import accuracy_score
ac_train = accuracy_score(Y_train,Y_pred_train)
ac_test = accuracy_score(Y_test,Y_pred_test)
  
print("Training Accuracy:",ac_train.round(2))
print("Test Accuracy:",ac_test.round(2))


Training Accuracy: 1.0
Test Accuracy: 1.0


In [16]:
import sklearn
print(sklearn.__version__)

1.3.2


In [21]:
#cross validation

from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=13)

training_accuracy =[]
test_accuracy = []

for i in range (1,100):
    X_train,X_test,Y_train,Y_test = train_test_split(SS_X,Y,test_size=0.30,
                                                    random_state=i)
    KNN.fit(X_train,Y_train)
    Y_pred_train = KNN.predict(X_train)
    Y_pred_test = KNN.predict(X_test)


training_accuracy.append(accuracy_score(Y_train,Y_pred_train))
test_accuracy.append(accuracy_score(Y_test,Y_pred_test))
print("Cross validation training results:",np.mean(training_accuracy).round(2))
print("Cross validation test results:",np.mean(test_accuracy).round(2))





Cross validation training results: 0.91
Cross validation test results: 0.97


In [22]:
#pd.DataFrame(training_accuracy).hist()   
k1 = pd.DataFrame(training_accuracy)
k1.skew()
k1.mean()
print("Cross validation training results:",k1.mean().round(2))
#pd.DataFrame(test_accuracy).hist()   
k1 = pd.DataFrame(test_accuracy)
k1.skew()
k1.mean()
print("Cross validation test results:",k1.mean().round(2))



Cross validation training results: 0    0.91
dtype: float64
Cross validation test results: 0    0.97
dtype: float64
